apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-equipments-view
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Equipments Management"
    rbac.authorization.halo.run/ui-permissions: '["plugin:equipments:view"]'
    rbac.authorization.halo.run/display-name: "装备查看"
rules:
  - apiGroups: [ "equipments.halo.run"]
    resources: [ "equipments" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.plugin.halo.run"]
    resources: [ "plugins/equipments" ]
    resourceNames: [ "PluginEquipments" ]
    verbs: [ "get", "list" ]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-equipments-manage
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: '["role-template-equipments-view"]'
    rbac.authorization.halo.run/ui-permissions: '["plugin:equipments:manage"]'
    rbac.authorization.halo.run/module: "Equipments Management"
    rbac.authorization.halo.run/display-name: "装备管理"
rules:
  - apiGroups: [ "equipments.halo.run"]
    resources: [ "equipments" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
  - apiGroups: [ "api.plugin.halo.run"]
    resources: [ "plugins/equipments" ]
    resourceNames: [ "PluginEquipments" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
