apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginEquipments
spec:
  enabled: true
  version: 1.2.0
  requires: ">=2.8.0"
  author:
    name: 困困鱼
    website: https://kunkunyu.com
  logo: logo.svg
  homepage: https://github.com/halo-sigs/plugin-equipments
  configMapName: plugin-equipments-configmap
  settingName: plugin-equipments-settings
  displayName: "我的装备管理"
  description: "我的装备管理模块"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-equipments/blob/main/LICENSE"
